#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+OPTIONS: toc:2
#+author: lockbox


* Posts
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

#+begin_description
 Neat little tricks and things I've learned (or had to relearn) about computers
#+end_description


*  Reasoning with Dafny :@dafny:
:PROPERTIES:
:EXPORT_FILE_NAME: elementary-reasoning-dafny
:END:


* TODO Programming Resources :resources:
Articles, blog posts, and information that might be useful at some point
** Programming rants and blogs (generic)
:PROPERTIES:
:EXPORT_FILE_NAME: generic-programming-rants-and-blogs
:END:
- [C is Not a Low-Level Language](https://queue.acm.org/detail.cfm?id=3212479)
- [Compile-time Detection of Atomic Context Violations for Kernel Rust Code](https://www.memorysafety.org/blog/gary-guo-klint-rust-tools/)
- [What every C programmer should know about UB](http://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html)
- [The Importance of Logging](https://www.thecodedmessage.com/logging/)
- [Patterns and Abstractions](https://without.boats/blog/patterns-and-abstractions/)
- [Zig Project Managment](https://blog.orhun.dev/zig-bits-03/)
- [Intro to rseq](https://google.github.io/tcmalloc/rseq.html)
- [Battleye shellcode RE](https://secret.club/2020/03/31/battleye-developer-tracking.html)
- [Match de-obfuscation and equality saturation](https://secret.club/2022/08/08/eqsat-oracle-synthesis.html)
- [Linker Scripts](https://mcyoung.xyz/2021/06/01/linker-script/)
- [The axioms of Linking](https://rosshemsley.co.uk/posts/linking/)
- [What I've learned about formal methods in half a year](https://jakob.space/blog/what-ive-learned-about-formal-methods.html)
- [TI Calculator Hobbyists](https://www.thirtythreeforty.net/posts/2021/10/ti-calculator-innovation/)
- [System emulation detection](https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html)
- [python refurb](https://github.com/dosisod/refurb)
- [making an executable mutation engine](https://blog.back.engineering/13/04/2022/)
** Pieces of Eight
:PROPERTIES:
:EXPORT_FILE_NAME: gold-pieces
:END:
 Random pieces and tidbits that are gold in the split second when you need the refresher

*** emacs
- multiline cursor or "[column text rectangles](http://xahlee.info/emacs/emacs/emacs_string-rectangle_ascii-art.html)"
- emacs tramp to docker dev container [here](https://happihacking.com/blog/posts/2023/dev-containers-emacs/)


* Playdate Hacking :@playdate:
Hacking and Tinkering with the [Playdate](https://play.date) game console.

** The state of Playdate in JAN 2024
:PROPERTIES:
:EXPORT_FILE_NAME: state-of-playdate
:EXPORT_DATE: 2024-01-14
:END:

The last time i messed around with the =Playdate= (~1 year ago -- [pd-platform](https://pd-platform.lockbox.sh)), the
OS version was =1.x=, and there was only 1 released version of the console. Now there are 2
different hardware revisions (the difference being the processor model), and the OS has
been updated to a =2.x= revision to reflect that (see [this](https://news.play.date/news/playdate-os-2-group-4/)
blog post).

*** 2024 Playdate
There's now a [game catalog](https://play.date/games/), where you can purchase games
to automatically sideload them, along with the advent of a new container file format
[supporting encryption](https://github.com/cranksters/playdate-reverse-engineering/blob/eb67dc3b418cbd9c9473b27954ba2180e317b01a/formats/pdz.md).
And a [new =pdex.bin= format](https://github.com/castholm/playdate-reverse-engineering/blob/ce53c12308ed2f4fdf1945377ec3145827118fd2/formats/pdex.md).

There have also been an uptick in memory-related issues in pd-OS / =BERNARD= if they still
call it that.

- <https://devforum.play.date/t/c-api-sampleplayer-setsample-causing-memory-leaks/14568>
- <https://devforum.play.date/t/clearing-image-tables-crashes-the-simulator-console/15282/2>

Also of note are some off-by-one related issues:
- <https://devforum.play.date/t/2-2-0-launcher-discrepancy-in-launcher-cards-loopcount/15464>
- <https://devforum.play.date/t/drawrotatedbitmap-rendering-error-when-rendering-out-of-bounds-at-specific-angles/4809/5>
- <https://devforum.play.date/t/drawrotatedbitmap-draws-from-wrong-center-if-degrees-is-one-of-the-four-cardinal-directions/3620/10>
- <https://devforum.play.date/t/playdate-timer-value-increases-between-calling-pause-and-start/2096/18>
- <https://devforum.play.date/t/playdate-sprite-with-odd-dimensioned-images-drawn-off-by-1-when-x-y-position-offscreen/8312/5>

And it still looks like that there's no method for real exception handling yet.

Things that the community seem's to still be desperate for network connectivity and the open-sourcing
of the lua SDK. Though it also looks like the lua sdk is at a point where much of it is getting
turned into thin wrappers over C-routines. IMO this could be a prime candidate to provide error-handling
for developers (a la something like [this](https://www.lua.org/pil/8.4.html)). Though at the same time
doing that in C would probably be the way to go, because then the lua wrappers would just mirror
the reponses. Either way, a /huge/ QoL improvement would be returning errors instead of just
crashing.

All in all, it's exciting to see that the Playdate continues to have an active community and
a responsive dev team, and that the ecoystem of tools and libraries is continuing to improve.

With me now having a new hardware revision in addition to the first revision, it's time to start
hacking on the playdate again.


*** Looking forward

Hopefully I'll have enough free time to check these new pieces of the Playdate out:
- documenting the new =pdex.bin= file format w some examples
- making some bindings to available userspace code outside of the SDK
- moving all my tooling to ghidra (I am not a fan of the Binary Ninja file loaders and its annoying to dev on, with little room for real testing of loader plugin code)
- finish documenting firmware update process (realistically ill probably have to restart)
